on:
  - pull_request_target
jobs:
  doc-extension-check:
    runs-on: ubuntu-latest
    steps:
      - name: doc-extension-check
        shell: bash {0}
        run: |
          MDFILES=$(curl -sL ${{ github.event.pull_request.patch_url }} | grep -P '^ create mode \d* website\/.*\/\w*\.markdown')

          if [ -n "$MDFILES" ]
          then
            echo "Documentation files must have the extension *.html.markdown"           
            exit 1
          else
            exit 0
          fi
