on:
  - pull_request_target
jobs:
  checker:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - run:
          sudo apt-get install ripgrep
      - name: doc-extension-check
        shell: bash {0}
        run: |
          MDFILES=$(curl -sL ${{ github.event.pull_request.patch_url }} | rg -U '^ create mode \d* website/.*/\w*.markdown\n')

          if [ -n "$MDFILES" ]
          then
            echo "Documentation files must have the extension *.html.markdown"           
            exit 1
          else
            exit 0
          fi
