on:
  - pull_request_target
jobs:
  checker:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
