on:
  push:
    branches:
      - master
name: Add merged PRs to current mileston
jobs:
  AddMergedToCurrentMilestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            echo ::set-output name=current_milestone::$(cat CHANGELOG.md | head -1 | cut -d " " -f 2)
      - run: echo ${{ steps.vars.outputs.current_milestone }}
