on:
  pull_request_review:
    types: [submitted]
jobs:
  dummy-workflow:
    runs-on: ubuntu-latest
    name: dummy workflow
    steps:
      - name: Explanation
        run: echo "Dummy Workflow"       
