on:
  pull_request:
    types: [closed]
name: Add changelog notes
jobs:
  ParseChangelog:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export previoustag="$(git describe --abbrev=0 --match='v*.*.*' --tags)"
          echo ::set-output name=milestone_id::"$(git rev-list -n 1 $previoustag)"
