on:
  pull_request:
    types: [closed]
name: Add changelog notes
jobs:
  ParseChangelog:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: breathingdust/previous-release-action@v1
        id: parse-changelog
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: 'CHANGELOG.md'
      - uses: actions/setup-go@v2
      - run: go get github.com/hashicorp/go-changelog/cmd/changelog-build
      - run: changelog-build ${{ env.GITHUB_SHA}} ${{ steps.parse-changelog.outputs.previous_sha }}
