on:
  pull_request:
    types: [closed]
name: Add changelog notes
jobs:
  ParseChangelog:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
          export previoustag="$(git describe --abbrev=0 --match='v*.*.*' --tags)"
          echo ::set-output name=previous-release-sha::"$(git rev-list -n 1 $previoustag)"
        id: get-previous-release-sha
      - run: echo 
      - run: |
          go get github.com/hashicorp/go-changelog/cmd/changelog-build
          $(go env GOPATH)/bin/changelog-build -this-release $(git rev-parse HEAD) -last-release ${{ steps.get-previous-release-sha.outputs.previous-release-sha }}
