name: CHANGELOG Checks
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    paths:
      - .changelog/*
      - .go-version
      - CHANGELOG.md
  pull_request_target:

env:
  GO111MODULE: on

jobs:
  changelog-check:
    # If there  a `pr/no-changelog` label we ignore this check
    if: "!${{ contains(github.event.pull_request.labels.*.name, 'pr/no-changelog')}}"
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.pull_request.labels.*.name}}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: Check for changelog entry in diff
        run: |
          # check if there is a diff in the .changelog directory
          changelog_files=$(git --no-pager diff --name-only HEAD "$(git merge-base HEAD "origin/${{ github.event.pull_request.base.ref }}")" -- .changelog/)
          # If we do not find a file in .changelog/, we post a comment to the PR
          if [ -z "$changelog_files" ]; then
            exit 1
          else
            echo "changelog-check: Found .changelog entry in PR!"
          fi
