on:
  pull_request:
    types: [closed]
name: Add changelog notes
jobs:
  ParseChangelog:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: breathingdust/previous-release-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: 'CHANGELOG.md'
