name: CHANGELOG Checks
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .changelog/*
      - go.sum
      - CHANGELOG.md
  pull_request_target:

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit

  changes:
    needs: community_check
    name: Filter Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        if: github.event_name == 'pull_request_target' && needs.community_check.outputs.maintainer == 'true'
        id: filter
        with:
          filters: |
            changed:
              - CHANGELOG.md

  comment:
    needs: changes
    if: needs.changes.outputs.changed
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Find Existing PR Comment
        id: prc
        uses: peter-evans/find-comment@034abe94d3191f9c89d870519735beae326f2bdb
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Please note that the `CHANGELOG.md` file contents are handled by the maintainers during merge"
      - run: echo ${{ steps.prc.outputs.comment-id }}
      - name: PR Comment
        if: steps.prc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            Thank you for your contribution! :rocket:

            Please note that the `CHANGELOG.md` file contents are handled by the maintainers during merge. This is to prevent pull request merge conflicts, especially for contributions which may not be merged immediately. Please see the [Contributing Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing) for additional pull request review items.

            Remove any changes to the `CHANGELOG.md` file and commit them in this pull request to prevent delays with reviewing and potentially merging this pull request.
