name: Changelog

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  update-changelog:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

 
