
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
name: Firewatch
jobs:
  FirewatchJob:
    runs-on: ubuntu-latest
    steps:
    - name: DownloadArtifact
      uses: actions/download-artifact@v2
      with:
        name: firewatch
      continue-on-error: true
    - name: Firewatch
      uses: breathingdust/firewatch@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        org: testorg-ghprovider
        repo: ghaction-test
        alert_threshold: 1
        firewatch_data: firewatch.data
        issue_age_months: 1
        slack_token: 1
        slack_channel: 1
    - name: UploadArtifact
      uses: actions/upload-artifact@v2
      with:
        name: firewatch
        path: firewatch.data
        if-no-files-found: error
