
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
name: Firewatch
jobs:
  FirewatchJob:
    runs-on: ubuntu-latest
    steps:
    - name: Firewatch
      uses: breathingdust/firewatch@d44ea4b76b7ed38b97cfe8b0388cfc249ef1c7f2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        alert_threshold: 1
        issue_age_months: 1
        slack_token: 1
        slack_channel: 1
    - name: UploadArtifact
      uses: actions/upload-artifact@v2
      with:
        name: firewatch
        path: firewatch.data
        if-no-files-found: error
        retention-days: 1
