
on:
  workflow_dispatch:
name: Firewatch
jobs:
  DownloadArtifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: firewatch
      continue-on-error: true
