name: "List Check"
on:
  pull_request:
   types: [assigned, opened, synchronize, reopened]
jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit
  Test:
    needs: community_check
    runs-on: ubuntu-latest
    steps:
      - name: Notification PR Merged
        run: |
          echo ${{ needs.community_check.outputs.maintainer }}
