name: Team Open PR Counts

on:
  schedule:
    - cron:  '0 3 * * 1-5'

jobs:
  open-pr-stats:
    runs-on: ubuntu-latest
    name: Open PRs for Team Members
    steps:
    - name: open-pr-stats
      uses: breathingdust/github-team-slackbot@v13
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN}}
        org: terraform-providers
        team_slug: aws-provider
        slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel: ${{ secrets.SLACK_CHANNEL }}
