# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tf_aws_prov_stats:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: stats
      uses: breathingdust/tf-aws-provider-team-stats@v4
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN}}
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.stats.outputs.stats }}"
