# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  tf_aws_prov_stats:
    runs-on: ubuntu-latest
    name: Open PRs for Team Members
    steps:
    - name: stats
      uses: breathingdust/tf-aws-provider-team-stats@v9
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN}}
        org: terraform-providers
        team_slug: aws-provider
      id: stats
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{"channel":"C015HGC9LBU","text":"${{ steps.stats.outputs.stats_message}}"}'

