on:
  project_card:
    types: [moved]
env:
  HC_REVIEW_COLUMN_ID: '11197351'
  WORKING_BOARD_COLUMN_ID: '19410840'
  GH_TOKEN: ${{ github.token }}
jobs:
  AWSContributionReady:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ env.HC_REVIEW_COLUMN_ID }} ${{ toJson(github.event) }}"
      - name: Get PullRequest name
        id: get-name
        if: github.event.project_card.column_id == env.HC_REVIEW_COLUMN_ID
        run: |
          PR=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.event.project_card.content_url }} )
          PR_NAME=$($PR | jq .html_url | tr -d '"')
          HTML_URL=$($PR | jq .html_url | tr -d '"')
          PR_ID=$($PR | jq .html_url | tr -d '"')
          echo "PR_ID=$PR_ID" >> $GITHUB_OUTPUT
          echo "PR_NAME=$PR_NAME" >> $GITHUB_OUTPUT
          echo "HTML_URL=$HTML_URL" >> $GITHUB_OUTPUT
      - name: Feed Message
        if: github.event.project_card.column_id == env.HC_REVIEW_COLUMN_ID
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":aws-cool: AWS Contribution: <${{ steps.get-name.outputs.HTML_URL }}|${{ steps.get-name.outputs.PR_NAME }}> has been marked as ready for HashiCorp review."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: AddToWorkingBoard
        if: github.event.project_card.column_id == env.HC_REVIEW_COLUMN_ID
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /projects/columns/${{ env.WORKING_BOARD_COLUMN_ID }}/cards \
          -f content_id='${{ steps.get-name.outputs.PR_ID }}'
