on:
  project_card:
    types: [moved]
env:
  HC_REVIEW_COLUMN_ID: '11197351'
  WORKING_BOARD_COLUMN_ID: '19410840'
jobs:
  AWSContributionReady:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ env.HC_REVIEW_COLUMN_ID }} ${{ toJson(github.event) }}"
      - name: Get PullRequest name
        if: github.event.column_id == env.HC_REVIEW_COLUMN_ID
        run: |
          PR_NAME=$(gh pr view ${{ github.event.project_card.content_url }} --json title | jq .title)
          echo "PR_NAME=$PR_NAME" >> $GITHUB_ENV
      - name: Feed Message
        if: github.event.column_id == env.HC_REVIEW_COLUMN_ID
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "AWS Contribution :tag: <https://github.com/${{ github.event.project_card.content_url }}|${{ env.PR_NAME }}> has been marked as ready for HashiCorp review."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          PR_NAME: ${{ env.PR_NAME }}
      - name: AddToWorkingBoard
        if: github.event.column_id == env.HC_REVIEW_COLUMN_ID
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /projects/columns/${{ env.WORKING_BOARD_COLUMN_ID }}/cards \
          -f content_url='${{ github.event.project_card.content_url }}'
        env:
          GH_TOKEN: ${{ github.token }}
