name: Resource Counts
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  coverage:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: |
          touch main.tf
          cat << EOF > main.tf
          terraform {
          required_providers {
          aws = {
          source  = "hashicorp/aws"
          }
          }
          }
          EOF
      - run: terraform init
      - run: |
          datasources=$(terraform providers schema -json | jq '.provider_schemas[] .data_source_schemas | length')
          resources=$(terraform providers schema -json | jq '.provider_schemas[] .resource_schemas | length')
          echo $datasources
          echo $resources
          sed -r -i "s/There are currently ([0-9]+) resources and ([0-9]+)(.*)/There are currently $resources resources and $datasources\3/" website/docs/index.html.markdown
          git status
