name: If roadmap milestone is assigned, add to working board. 
on:
  issues:
    types: [milestoned]
jobs:
  AddRoadmapItemsToBoard:
    runs-on: ubuntu-latest
    steps:
    - name: Move Roadmap Items To Working Board
      uses: alex-page/github-project-automation-plus@v0.8.1
      if: github.event.issue.milestone.title == 'Roadmap'
      with:
        project: Test Project
        column: To Do
        repo-token: ${{ secrets.GH_TOKEN}}
