on:
  - pull_request
name: RoundRobin
jobs:
  MaintainerPRAssign:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' && contains(fromJSON('["breathingdust"]'), github.actor)
    steps:
      - run: |
          PREVIOUS_RUN_ID=$(curl -sL -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/testorg-ghprovider/ghaction-test/actions/workflows/roundrobin.yml/runs | jq -r '.workflow_runs[0].id?')
          echo $PREVIOUS_RUN_ID
          
          if [[ ! -z $PREVIOUS_RUN_ID ]]
          then
            echo "1"
          fi  
          
          if [[ $PREVIOUS_RUN_ID == "null" ]]
          then
            echo "2"
          fi             

      - uses: actions/upload-artifact@v2
        name: upload
        with:
          name: roundrobin
          path: roundrobin
